name: Approve proposal

on:
  issues:
    types: [labeled]

jobs:
  add_term:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Mostra informazioni di debug
      - name: Show issue info
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue body: ${{ github.event.issue.body }}"

      # 4️⃣ Aggiorna definitions.json con lo script Python
      - name: Add term to definitions.json
        run: |
          python scripts/append_term.py \
            "${{ github.event.issue.title }}" \
            "${{ github.event.issue.body }}"

      # 5️⃣ Mostra il contenuto aggiornato del JSON
      - name: Show definitions.json
        run: cat definitions.json

      # 6️⃣ Mostra differenze prima del commit
      - name: Show git diff
        run: git diff

      # 7️⃣ Commit e push in sicurezza
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add definitions.json
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Add approved term from issue #${{ github.event.issue.number }}"
            git push
          fi
